server:
  port: 8080
spring:  application:    name: demo-gateway
  cloud:
    nacos:      discovery:        server-addr: 127.0.0.1:8848    gateway:      discovery:        locator:          enabled: true
          lower-case-service-id: true      routes:      - id: demo-sso-client1
        uri: lb://demo-sso-client1        filters:        - StripPrefix=1 
        predicates:        - Path=/test1/**
      - id: demo-sso-client2
        uri: lb://demo-sso-client2
        filters:
        - StripPrefix=1
        - name: Retry
          args:            retries: 3
            status: 503
        predicates:
        - Path=/test2/**
security:  oauth2:    client:      access-token-uri: http://localhost:9901/oauth2/oauth/token 
      user-authorization-uri: http://localhost:9901/oauth2/oauth/authorize
    resource:      user-info-uri: http://localhost:9901/oauth2/user                                        
      