server:
  port: 9103
  
spring:
  application:
    name: demo-score
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   
#oracle  datasource:    url: jdbc:oracle:thin:@10.0.1.201:1521:cedata
    username: bpmuser
    password: bpmuser
    driver-class-name: oracle.jdbc.driver.OracleDriver        